---
- project:
    name: integration-docker-compose
    project-name: 'integration'
    project: 'integration'
    stream:
      - 'master':
          branch: 'master'
    jobs:
      - '{project-name}-{stream}-{subproject}-docker-compose-verify':
          script: |
            #!/bin/bash
            cd $DOCKER_ROOT
            docker-compose up -d
    subproject:
      - 'netconf-pnp-simulator':
          pattern: 'test/mocks/netconf-pnp-simulator/modules/**'
          docker_root: 'test/mocks/netconf-pnp-simulator/modules'
      - 'emssimulator-swm-netconf':
          pattern: 'test/mocks/emssimulator/swm-netconf/**'
          docker_root: 'test/mocks/emssimulator/swm-netconf'
          netconf_sim_service_name: 'ems-netconf-swm'
          post_script: !include-raw-escape: netconf-pnp-simulator-verify.sh
