---
- project:
    name: policy-drools-applications
    project-name: 'policy-drools-applications'
    jobs:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java':
          docker-pom: 'pom.xml'
          mvn-profile: 'docker'
          mvn-params: "-P docker"
      - '{project-name}-{stream}-docker-version-java-daily':
          docker-pom: 'pom.xml'
          mvn-profile: 'docker'
          mvn-params: '-P docker'
          disabled: true

    project: 'policy/drools-applications'
    stream:
      - 'master':
          branch: 'master'
    mvn-settings: 'policy-drools-applications-settings'
    files: '**'
    archive-artifacts: ''
    build-node: ubuntu1604-docker-8c-8g

- project:
    name: policy-drools-applications-dublin
    project-name: 'policy-drools-applications-dublin'
    jobs:
      - '{project-name}-{stream}-verify-java'
      - '{project-name}-{stream}-merge-java'
      - '{project-name}-{stream}-release-version-java-daily':
          disabled: false

    project: 'policy/drools-applications'
    stream:
      - 'dublin':
          branch: 'dublin'
    mvn-settings: 'policy-drools-applications-settings'
    files: '**'
    archive-artifacts: ''
    build-node: 'ubuntu1604-builder-4c-4g'

- project:
    name: policy-drools-applications-sonar
    jobs:
      - gerrit-maven-sonar
    cron: '@daily'
    build-node: ubuntu1604-builder-4c-4g
    project: 'policy/drools-applications'
    project-name: 'policy-drools-applications'
    branch: 'master'
    mvn-settings: 'policy-drools-applications-settings'
    mvn-goals: 'clean install'
    mvn-opts: '-Xmx1024m -XX:MaxPermSize=256m'

- project:
    name: policy-drools-applications-clm
    jobs:
      - gerrit-maven-clm
    nexus-iq-namespace: 'onap-'
    project: policy/drools-applications
    project-name: 'policy-drools-applications'
    branch: 'master'
    mvn-settings: 'policy-drools-applications-settings'

- project:
    name: policy-drools-applications-info
    project-name: policy-drools-applications
    jobs:
      - gerrit-info-yaml-verify
    project: policy/drools-applications
    branch: master
